create table tasks (
task_id	serial	primary key,
task_name	varchar(20)	not null,
task_status	varchar(10)	not null,
task_content	text not null,
task_no Integer	not null,
priority	varchar(5)	not null,
progress	Integer,
tag	text,
created_at	timestamp(3)	not null,
creator_id	Integer,
engineer_id	Integer,
project_id	Integer,
updated_at	timestamp(3)	not null,
anticipated_commencement_date	Date	not null,
expected_completion_date	Date	not null,
finish_date	Date,
completion_date	Date,
completion_flg	boolean	not null,
deleted_flg	boolean	not null
)